packages:
  - apps/api
  - apps/worker
  - packages/*

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  protobufjs: true

onlyBuiltDependencies:
  - "@prisma/engines"
  - prisma
  - protobufjs
